services:
#    gluetun:
#        image: qmcgaw/gluetun:latest
#        container_name: gluetun
#        cap_add:
#            - NET_ADMIN
#        env_file: .env
#        environment:
#            - VPN_SERVICE_PROVIDER=custom
#            - VPN_TYPE=openvpn
#            - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
#            - OPENVPN_USER=${KASPERSKY_USERNAME}
#            - OPENVPN_PASSWORD=${KASPERSKY_PASSWORD}
#            - TZ=America/Lima
#        volumes:
#            - ./credentials.ovpn:/gluetun/custom.conf:ro
#        ports:
#          - "9080:9080"          # UI qBittorrent
#          - "6881:6881"          # TCP BitTorrent
#          - "6881:6881/udp"      # UDP DHT
#          - "9117:9117"          # jackett ui
#          - "8191:8191"          # flaresolverr
#        restart: unless-stopped
#        networks:
#          mi-red:
#              external: true
    jellystat:
        image: cyfershepard/jellystat:latest
        container_name: jellystat
        environment:
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_IP: ${PG_HOST}
            POSTGRES_PORT: ${PG_PORT}
            POSTGRES_DB: ${PG_DATABASE}
            JWT_SECRET: ${JWT_SECRET_KEY}
            TZ: America/Lima
        ports:
            - "3000:3000"
        networks:
            - mi-red
    it-tools:
        image: corentinth/it-tools:latest
        container_name: it-tools
        ports:
            - "8080:80"
        restart: unless-stopped
        networks:
           - mi-red
networks:
    mi-red:
        external: true
