services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        env_file: .env
        environment:
            - VPN_SERVICE_PROVIDER=nordvpn
            - OPENVPN_USER=${NORD_USER}
            - OPENVPN_PASSWORD=${NORD_PASS}
            #            - SERVER_COUNTRIES=${NORD_COUNTRIES}
            - TZ=America/Lima
        volumes:
            - /home/rigo/gluetun:/gluetun
        ports:
            - "9080:9080"          # UI qBittorrent
            - "6881:6881"          # TCP BitTorrent
            - "6881:6881/udp"      # UDP DHT
            - "9117:9117"          # jackett ui
            - "8191:8191"          # flaresolverr
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"   # usa la misma pila de red
        depends_on:
            gluetun:
                condition: service_healthy
        env_file: .env
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=America/Lima
            - WEBUI_PORT=9080
        volumes:
            - /home/rigo/qbittorrent/config:/config
            - /media/RIGO8/Descargas:/downloads
        restart: unless-stopped

    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        network_mode: "service:gluetun"
        depends_on:
            gluetun:
                condition: service_healthy
        env_file: .env
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=America/Lima
        volumes:
            - /home/rigo/jackett/config:/config
        restart: unless-stopped

    jellystat:
        image: cyfershepard/jellystat:latest
        container_name: jellystat
        environment:
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_IP: ${PG_HOST}
            POSTGRES_PORT: ${PG_PORT}
            POSTGRES_DB: ${PG_DATABASE}
            JWT_SECRET: ${JWT_SECRET_KEY}
            TZ: America/Lima
        ports:
            - "3000:3000"
        networks:
            - mi-red

    it-tools:
        image: corentinth/it-tools:latest
        container_name: it-tools
        ports:
            - "8081:80"
        restart: unless-stopped
        networks:
            - mi-red

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
            - "53:53/tcp"                                          # DNS TCP
            - "53:53/udp"                                          # DNS UDP
            - "80:80/tcp"                                          # HTTP
            - "443:443/tcp"                                        # HTTPS
            # - "67:67/udp"                                        # DHCP, opcional
            # - "123:123/udp"                                      # NTP, opcional
        environment:
            TZ: 'America/Lima'
            FTLCONF_webserver_api_password: ${PIHOLE_API_PASSWORD}
            FTLCONF_webserver_port: ${PIHOLE_WEB_PORT}        # Puerto del webserver de Pi-hole
            FTLCONF_dns_listeningMode: 'all'                       # Modo de escucha DNS
            # FTLCONF_misc_etc_dnsmasq_d: 'true'                   # Para persistir /etc/dnsmasq.d si migras de v5
        volumes:
            - '/home/rigo/etc-pihole:/etc/pihole'                           # Persistencia de datos de Pi-hole
            # - './etc-dnsmasq.d:/etc/dnsmasq.d'                   # Persistencia de configuración adicional
        #        cap_add:
        # - NET_ADMIN   # Necesario solo si usas Pi-hole como DHCP server
        # - SYS_TIME    # Necesario solo para que pueda ajustar la hora del host
        # - SYS_NICE    # Opcional: para mayor prioridad de proceso
        restart: unless-stopped

    stirling-pdf:
        container_name: stirling-pdf
        image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
        ports:
            - '8082:8080'
        volumes:
            - /home/rigo/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
            - /home/rigo/StirlingPDF/extraConfigs:/configs
            - /home/rigo/StirlingPDF/customFiles:/customFiles/
            - /home/rigo/StirlingPDF/logs:/logs/
            - /home/rigo/StirlingPDF/pipeline:/pipeline/
        environment:
            - DISABLE_ADDITIONAL_FEATURES=false
            - LANGS=es_ES
            - UI_LANGUAGES='["es_ES"]'
            - SYSTEM_DEFAULTLOCALE=es-ES
        restart: unless-stopped
        networks:
            - mi-red

networks:
    mi-red:
        external: true
